version: '2'
services:
  calculator:
    build: ./calculator
    volumes:
      - ./calculator:/usr/app
    links:
      - rabbitmq
      
  calc-web:
    build: ./calc-web
    volumes:
      - ./calc-web:/usr/app
    ports:
      - "8080:8080"
    links:
      - rabbitmq
      
  rabbitmq:
    image: rabbitmq:alpine
    ports:
      - "5672:5672"
